spring:
  application:
    name: local-grpc-server
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password


grpc:
  server:
    port: 9898
server:
  port: 8057



eqhub:
  auth:
    secret: __secretkey&&__secretkey%%__secretkey//__
    exp:  3600000
