spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: '/api'
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eqhub

server:
  port: 8085


eqhub:
  auth:
    secret: __secretkey&&__secretkey%%__secretkey//__
    exp:  3600000