spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  webflux:
    base-path: '/api'
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eqhub

server:
  port: 8085