server:
  port: 8078

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: eqhub
  kafka:
    properties:
      spring.json.add.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092



eqhub:
  auth:
    secret: __secretkey&&__secretkey%%__secretkey//__
    exp:  3600000