spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: '/api'
  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: "earliest"
      properties:
        spring.json.value.default.type: org.dark.eqhub.postservice.writeapi.domain.model

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: eqhub
  cache:
    type: redis



server:
  port: 8085


eqhub:
  auth:
    secret: __secretkey&&__secretkey%%__secretkey//__
    exp:  3600000


grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext